name: First CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run simple command
        run: |
          echo "Hello from GitHub Actions"
          uname -a
